import MainLayout from "../components/Layout/MainLayout";
import Head from "next/head";
import ContentMenu from "@/components/LandingPage/ContentMenu";

export default function Home() {
  return (
    <>
      <Head>
        <title>Kalshi Market</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MainLayout>
        <ContentMenu />
      </MainLayout>
    </>
  );
}
